[greeter]
background = /usr/share/backgrounds/duckybox/duckybox-login.jpg
theme-name = Duckybox
icon-theme-name = Papirus-Dark
font-name = Sans 11
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %H:%M
position = 50%,center 76%,center
default-user-image = /usr/share/icons/duckybox/duckybox-256.png
hide-user-image = false
round-user-image = true
