[Greeter]
background = /usr/share/backgrounds/duckybox/duckybox-login.jpg
background-color = #12071F
theme-name = Duckybox
icon-theme-name = Papirus-Dark
font-name = Sans 11
draw-user-backgrounds = false
draw-grid = false
show-hostname = true
show-a11y = false
clock-format = %H:%M
activate-numlock = false
